# Tensorflow Practice  

  


In [2]:
import tensorflow as tf 
print(tf.__version__)

2.3.0


## Basic operations with TensorFlow

In [3]:
?tf.square

Signature: tf.square(x, name=None)
Docstring:
Computes square of x element-wise.

I.e., \\(y = x * x = x^2\\).

>>> tf.math.square([-2., 0., 3.])
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 0., 9.], dtype=float32)>

Args:
  x: A `Tensor`. Must be one of the following types: `bfloat16`, `half`, `float32`, `float64`, `int8`, `int16`, `int32`, `int64`, `complex64`, `complex128`.
  name: A name for the operation (optional).

Returns:
  A `Tensor`. Has the same type as `x`.

  If `x` is a `SparseTensor`, returns
  `SparseTensor(x.indices, tf.math.square(x.values, ...), x.dense_shape)`
File:      c:\users\19802\anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py
Type:      function


In [4]:
a = 4 + 2j # COMPLEX NUMBER  
b = 6 + 7j

print("a: ", a, "b: ", b, '\n')

print("a-b: ", a-b, '\n')
print("a*b: ", a*b, '\n')

c = a + b

print("c: ", c, '\n')

d = tf.square(c)
print(d, '\n')

a:  (4+2j) b:  (6+7j) 

a-b:  (-2-5j) 

a*b:  (10+40j) 

c:  (10+9j) 

tf.Tensor((19+180j), shape=(), dtype=complex128) 



### Tensors  
Tensors are an array of numbers arranged in space. We can call a vector (1-D array) as a 1st order tensor and matrix(2-D Array) as a 2nd order tensor and so on. 

In [5]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print("Elements: \n", c)

Elements: 
 tf.Tensor(
[[1.4 2.  2. ]
 [8.  2.  5. ]], shape=(2, 3), dtype=float32)


* You can get its value as a Numpy array, by calling `.numpy()`

In [6]:
import numpy as np
y = np.array([[1,2,2], [8, 2, 5]])
print(y)
# we can also convert a tensor into a numpy array by using .numpy()
c.numpy() 

[[1 2 2]
 [8 2 5]]


array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)

We can get the dimensions and the datatype of the a tf.tensor as demonstrated below- 

In [7]:
print('Tensor Data Type', c.dtype)
print('Tensor Dimension: ', c.ndim)
print('Tensor Shape', c.shape)

Tensor Data Type <dtype: 'float32'>
Tensor Dimension:  2
Tensor Shape (2, 3)


### Variables with tf.Variable()  
**A tensorflow Variable is a tensor that is used to store value that can later be updated.** You need to initalize a variable with some value at the time of creation. 

In [12]:
random_variable = tf.ones(shape=(3,3))

print("[INFO] type: ", type(random_variable))
print("[INFO] random_variable: ", random_variable, "\n")

# random variable
tf_variable = tf.Variable(random_variable)
print("[INFO] type: ", type(tf_variable))
print(tf_variable, '\n')

# you can now update the values of the variable
tf_variable.assign(tf.zeros(shape=(3,3)))
print(tf_variable)

[INFO] type:  <class 'tensorflow.python.framework.ops.EagerTensor'>
[INFO] random_variable:  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32) 

[INFO] type:  <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)> 

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


---

### GradientTapeGradientTape:  
The **[\`GradientTape\`]** which is used to record operations for automatic differentiation.  
[YouTube Video on GradientTape](https://www.youtube.com/watch?v=tDG52BjkGUY)

In [13]:
# computing derivative for the function 3x^2 at x = 3  


x = tf.constant(3.0) # gradient at  

with tf.GradientTape() as g: 
    g.watch(x) # record the operations  
    y = 3* x**2
    
dy_dx=g.gradient(y, x)
print("[INFO] dy_dx: ", dy_dx)

[INFO] dy_dx:  tf.Tensor(18.0, shape=(), dtype=float32)


In [14]:
# We can also use nested GradientTape() for the second derivative 
# computing second derivative for thet function 4x^3 at x = 4.0  

x = tf.constant(4.0)
with tf.GradientTape() as gt:
    gt.watch(x)
    with tf.GradientTape() as g:
        g.watch(x)  
        y=4* x**3  
        
    dy_dx = g.gradient(y, x)
d2y_d2x=gt.gradient(dy_dx, x)
print("[INFO] d2y_d2x: ", d2y_d2x)

[INFO] d2y_d2x:  tf.Tensor(96.0, shape=(), dtype=float32)


### Practice Questions


**1.Create a constant tensor array 'x' like [2,3,4] and find element wise e^x. Refer to the website [here](https://www.tensorflow.org/api_docs/python/tf/math/exp).**


**2. Declare a variable with a 3*2 shaped floating elements array with elements picked from a random normal distributions.**

**3. Subtract 1 from every element of the above matrix.**

**4. Calculate the third derivative of the function 4x^3 + x^2 + 1 at x = 1**

In [ ]:
#your code here
x = tf.constant(1.0) 

**5. Calculate dot product of matrices [[1,2,3],[4,5,6],[7,8,9]] and [[1],[2],[3]] using tensorflow functions. Also, find the element wise multiplication of the two.**

In [ ]:
#your code here for dot product
a = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
b = tf.constant([[1],[2],[3]])

https://www.kaggle.com/aggarwalrahul/dl-intro-to-nn-tensorflow-basics

---