# Tensorflow Practice  

  


In [1]:
import tensorflow as tf 
print(tf.__version__)

2.3.0


## Basic operations with TensorFlow

In [2]:
?tf.square

Signature: tf.square(x, name=None)
Docstring:
Computes square of x element-wise.

I.e., \\(y = x * x = x^2\\).

>>> tf.math.square([-2., 0., 3.])
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 0., 9.], dtype=float32)>

Args:
  x: A `Tensor`. Must be one of the following types: `bfloat16`, `half`, `float32`, `float64`, `int8`, `int16`, `int32`, `int64`, `complex64`, `complex128`.
  name: A name for the operation (optional).

Returns:
  A `Tensor`. Has the same type as `x`.

  If `x` is a `SparseTensor`, returns
  `SparseTensor(x.indices, tf.math.square(x.values, ...), x.dense_shape)`
File:      c:\users\19802\anaconda3\lib\site-packages\tensorflow\python\ops\gen_math_ops.py
Type:      function


In [7]:
a = 4 + 2j # COMPLEX NUMBER  
b = 6 + 7j

print("a: ", a, "b: ", b, '\n')

print("a-b: ", a-b, '\n')
print("a*b: ", a*b, '\n')

c = a + b

print("c: ", c, '\n')

d = tf.square(c)
print(d, '\n')

a:  (4+2j) b:  (6+7j) 

a-b:  (-2-5j) 

a*b:  (10+40j) 

c:  (10+9j) 

tf.Tensor((19+180j), shape=(), dtype=complex128) 



### Tensors  
Tensors are an array of numbers arranged in space. We can call a vector (1-D array) as a 1st order tensor and matrix(2-D Array) as a 2nd order tensor and so on. 

In [9]:
c = tf.constant([[1.4, 2.0, 2], [8, 2, 5]])
print("Elements: \n", c)

Elements: 
 tf.Tensor(
[[1.4 2.  2. ]
 [8.  2.  5. ]], shape=(2, 3), dtype=float32)


* You can get its value as a Numpy array, by calling `.numpy()`

In [11]:
import numpy as np
y = np.array([[1,2,2], [8, 2, 5]])
print(y)
# we can also convert a tensor into a numpy array by using .numpy()
c.numpy() 

[[1 2 2]
 [8 2 5]]


array([[1.4, 2. , 2. ],
       [8. , 2. , 5. ]], dtype=float32)

We can get the dimensions and the datatype of the a tf.tensor as demonstrated below- 

In [12]:
print('Tensor Data Type', c.dtype)
print('Tensor Dimension: ', c.ndim)
print('Tensor Shape', c.shape)

Tensor Data Type <dtype: 'float32'>
Tensor Dimension:  2
Tensor Shape (2, 3)
